### ISSUE TITLE
Checking for free space uses wrong target

### ISSUE THREAD

**Issue by mightypanders** [XorTroll/Goldleaf#240]
I tried installing a Split NSP to the System NAND, which did not work due to insufficient free space.

The NSP is 5,5 GB in size.
System NAND has 26,37 GB free.
SD Card has 18,19 GB free.
The installer wanted 10,45 GB of free space.

I tried installing a smaller NSP to System NAND (Retroarch 1.7.6) which is around 10 MB which installed without issue. 
Am I wrong in assuming that the "Console Memory (NAND)" shown in the Console Information Menu should be the value that is used for checking for free space or is installing to NAND discouraged?

**Comment by XorTroll** [comment]
True, NAND USER and NAND SYSTEM are swapped. Will fix this tomorrow.

**Comment by XorTroll** [comment]
Latest commit should fix this

**Comment by doomtrigger** [comment]
> Latest commit should fix this

Its still doing it dad

**Comment by maskmark** [comment]
no, commit #d212c5a didn't fix it!
the installer still requests double  of free size than the nsp installation actually needs when installing into nand or sdcard. my sdcard has 15gb and my nand has 17gb of free space,but goldleaf 0.5 nightly build refuses to intall a 9.4gb nsp because of no enough free space.
and when I deleted some files till I make 20gb spaces, goldleaf let me install the nsp.
so it is still something wrong.

**Comment by XorTroll** [comment]
Latewst commits don't check double size.
