### ISSUE TITLE
[7.0.0] Atmosphere 0.8.4: Can't install nsps: Failed to open the meta NCA CNMT NCA: 0x234c02

### ISSUE THREAD

**Issue by Jezziel** [XorTroll/Goldleaf#260]
As I stated on the article, I can't install any NSP or XCI games on my console, any leads?

**Comment by XorTroll** [comment]
3 questions:
- Do you have sigpatches?
- Fails on every NSP?
- USB installs or regular ones?
Btw, XCI isn'tn supported.

**Comment by Jezziel** [comment]
Hey there! Thanks for your reply, btw I'm new to these things and I wouldn't call myself as an advanced user, spare my ignorance; what are sigpatches?
#2: I tried a few NSPs and every single method has been failed to install.
I converted XCI files to NSPs and still couldn't complete the installation.

**Comment by XorTroll** [comment]
Sigpatches = some patches which are applied to atmosphere to allow installs and other content-related things.
You can get them from GBAtemp, just Google a little bit.

**Comment by trevor7oaks** [comment]
I have the same issue. I’m on 7.01, Atmosphere 0.8.4, Goldleaf V3. Tried about 15 nsps and got the same error. I have the sig patches

**Comment by XorTroll** [comment]
Only 0.5 supports installs on 7.x.

**Comment by trevor7oaks** [comment]
Ah ok, thanks

**Comment by renatosk** [comment]
I have sigpatches , got the same error as OP in every USB installs on 0.5 , on 0.3 works fine trough

**Comment by Jezziel** [comment]
> I have the same issue. I’m on 7.01, Atmosphere 0.8.4, Goldleaf V3. Tried about 15 nsps and got the same error. I have the sig patches

where did you get the sigpatches? I can't find any of them for 7.0.0

**Comment by renatosk** [comment]
with latest nightly i dont get more invalid nca magic , i get two errors: one is when i use goldtree ,goldleaf get stuck in "connection was established.Waiting for a NSP request from PC client..." , and the other is when i use fluffly , i get the error 0x202 , description: invalid path (1)

**Comment by ss5gamer** [comment]
Hello All I'm dealing with a issue. I currently have 7.0.1 I'm using gold lead v5 to install my nsp. When i try to launch all of my games except for like 3 of them I get a popup  (checking if software can be played)after that it goes to unable to connect to internet please check your setting. I'm not sure why it wants to connect to play the game, I did not get any error when installing the nsp through sd card on goldleaf and randomly 3 of the installed games worked.

**Comment by trevor7oaks** [comment]
You neeed to unarchive your sd, either via hekate or in windows properties. I had this and this solved it. You will need to delete the games from the switch and reinstall the nsps, but then will be fine

**Comment by ss5gamer** [comment]
@trevor7oaks it worked.. thank you so much!

**Comment by IncrediblblblCzero** [comment]
> You neeed to unarchive your sd, either via hekate or in windows properties. I had this and this solved it. You will need to delete the games from the switch and reinstall the nsps, but then will be fine

Who do you mean by "unarchive your sd" ? i don't get it.

**Comment by ss5gamer** [comment]
@IncrediblblblCzero I just booted my switch normally and put it in recovery mode. Then deleted everything except for the saved files, I reformatted the sd card via the switch and re-dropped the latest atmosphere and it works now.

**Comment by lookye** [comment]
@Jezziel @ss5gamer 
If you update Goldleaf to the latest 0.5 release. Everything should then work as intended for you.
Can this "Issue" then be closed?

**Comment by ss5gamer** [comment]
My issue was resolved. This can be closed.

**Comment by ProSparrow** [comment]
Unfortunately the issue persists with me. Used the sigpatches that come with kosmos v12.

**Comment by lookye** [comment]
@ProSparrow Do you use the 0.5 release version of Goldleaf?

**Comment by ProSparrow** [comment]
> @ProSparrow Do you use the 0.5 release version of Goldleaf?

Yes

**Comment by kevin791129** [comment]
I'm on 7.0.1 using atmosphere 0.8.9, using goldleaf 0.5 have sigpatches, but I get the same error with description invalid NCA.
Can install some NSPs no problem but the error occurs when trying to install newer games.

**Comment by james-d-elliott** [comment]
There are major USB issues isolated to HOS 7.0.x so if you're running 7.0.x just update (or downgrade if you'd prefer and know what you're doing).

**Comment by G0A** [comment]
> There are major USB issues isolated to HOS 7.0.x so if you're running 7.0.x just update (or downgrade if you'd prefer and know what you're doing).

source ?

**Comment by james-d-elliott** [comment]
https://github.com/Atmosphere-NX/Atmosphere/issues/509
